# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-02 16:02
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0018_camper_paid_dues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikemutationschedule',
            options={'ordering': ('event', 'date')},
        ),
        migrations.AlterField(
            model_name='meal',
            name='kind',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Midnight', 'Midnight BBQ'), ('Night Bar', 'Night Bar')], default='Dinner', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='sleeping_arrangement',
            field=models.CharField(choices=[('dunno', 'Not sure yet'), ('bringing', 'Bringing own tent'), ('car', 'Sleeping in own vehicle'), ('yurt', 'Using camp yurt (must reserve with Yurt Organizer)'), ('own_yurt', 'Using your own yurt'), ('sharing', "Sharing someone else's"), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
